# -*- coding: utf-8 -*-
"""MANCA - Encoder/DecoderSept30.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rMTP0SyqHCHhYHJKm9C3BBBd0fm1fkYB
"""

# Giuliana's Encoder/Decoder Ring
# I'm sorry...I got carried away!
def cloak(message, key, pin):
  encoded = ""
  vowels = [65, 69, 73, 79, 85, 89, 97, 101, 105, 111, 117, 121]
  commons = [83, 115, 84, 116, 82, 114]
  for letter in message:
    code = ord(letter)
    if code in vowels:
      new_code = code + key
      encoded = encoded + chr(new_code)
    else: 
        if code in commons:
          newc = code + pin
          encoded = encoded + chr(newc)
        else:
            encoded = encoded + chr(ord(letter))
  return encoded

def decloak(message, key, pin):
  encoded = ""
  vowels = [65, 69, 73, 79, 85, 89, 97, 101, 105, 111, 117, 121]
  commons = [83, 115, 84, 116, 82, 114]
  for letter in message:
    code = ord(letter)
    if (code + key) in vowels:
      new_code = code + key
      encoded = encoded + chr(new_code)
    else: 
        if (code + pin) in commons:
          newc = code + pin
          encoded = encoded + chr(newc)
        else:
            encoded = encoded + chr(ord(letter))
  return encoded


def hide(message):
  return cloak(message, 1500, 9000)

def seek(message):
  return decloak(message, -1500, -9000)



hide('Lolita, light of my life, fire of my loins. My sin, my soul. Lo-lee-ta: the tip of the tongue taking a trip of three steps down the palate to tap, at three, on the teeth. Lo. Lee. Ta. She was Lo, plain Lo, in the morning, standing four feet ten in one sock. She was Lola in slacks. She was Dolly at school. She was Dolores on the dotted line. But in my arms she was always Lolita. Did she have a precursor? She did, indeed she did. In point of fact, there might have been no Lolita at all had I not loved, one summer, an initial girl-child. In a princedom by the sea. Oh when? About as many years before Lolita was born as my age was that summer. You can always count on a murderer for a fancy prose style. Ladies and gentlemen of the jury, exhibit number one is what the seraphs, the misinformed, simple, noble-winged seraphs, envied. Look at this tangle of thorns.')

seek('Lًlم⎜ؽ, lمgh⎜ ًf mٕ lمfف, fم⎚ف ًf mٕ lًمn⎛. Mٕ ⎛مn, mٕ ⎛ًّl. Lً-lفف-⎜ؽ: ⎜hف ⎜مp ًf ⎜hف ⎜ًngّف ⎜ؽkمng ؽ ⎜⎚مp ًf ⎜h⎚فف ⎛⎜فp⎛ dًwn ⎜hف pؽlؽ⎜ف ⎜ً ⎜ؽp, ؽ⎜ ⎜h⎚فف, ًn ⎜hف ⎜فف⎜h. Lً. Lفف. ⍼ؽ. ⍻hف wؽ⎛ Lً, plؽمn Lً, مn ⎜hف mً⎚nمng, ⎛⎜ؽndمng fًّ⎚ fفف⎜ ⎜فn مn ًnف ⎛ًck. ⍻hف wؽ⎛ Lًlؽ مn ⎛lؽck⎛. ⍻hف wؽ⎛ Dًllٕ ؽ⎜ ⎛chًًl. ⍻hف wؽ⎛ Dًlً⎚ف⎛ ًn ⎜hف dً⎜⎜فd lمnف. Bّ⎜ مn mٕ ؽ⎚m⎛ ⎛hف wؽ⎛ ؽlwؽٕ⎛ Lًlم⎜ؽ. Dمd ⎛hف hؽvف ؽ p⎚فcّ⎚⎛ً⎚? ⍻hف dمd, مndففd ⎛hف dمd. إn pًمn⎜ ًf fؽc⎜, ⎜hف⎚ف mمgh⎜ hؽvف bففn nً Lًlم⎜ؽ ؽ⎜ ؽll hؽd إ nً⎜ lًvفd, ًnف ⎛ّmmف⎚, ؽn مnم⎜مؽl gم⎚l-chمld. إn ؽ p⎚مncفdًm bٕ ⎜hف ⎛فؽ. ثh whفn? \u061dbًّ⎜ ؽ⎛ mؽnٕ ٕفؽ⎚⎛ bفfً⎚ف Lًlم⎜ؽ wؽ⎛ bً⎚n ؽ⎛ mٕ ؽgف wؽ⎛ ⎜hؽ⎜ ⎛ّmmف⎚. صًّ cؽn ؽlwؽٕ⎛ cًّn⎜ ًn ؽ mّ⎚dف⎚ف⎚ fً⎚ ؽ fؽncٕ p⎚ً⎛ف ⎛⎜ٕlف. Lؽdمف⎛ ؽnd gفn⎜lفmفn ًf ⎜hف jّ⎚ٕ, فxhمbم⎜ nّmbف⎚ ًnف م⎛ whؽ⎜ ⎜hف ⎛ف⎚ؽph⎛, ⎜hف mم⎛مnfً⎚mفd, ⎛مmplف, nًblف-wمngفd ⎛ف⎚ؽph⎛, فnvمفd. Lًًk ؽ⎜ ⎜hم⎛ ⎜ؽnglف ًf ⎜hً⎚n⎛.')